# Generated by Django 5.2.10 on 2026-02-17 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicbody', '0050_alter_publicbody_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressConferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Press Conference Category',
                'verbose_name_plural': 'Press Conference Categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.CreateModel(
            name='PressConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('source_url', models.URLField(blank=True, verbose_name='source URL')),
                ('source_file', models.FileField(blank=True, upload_to='pressconferences')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_pressconference.pressconferencecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'press conference',
                'verbose_name_plural': 'press conferences',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('press_conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='froide_pressconference.pressconference', verbose_name='press conference')),
                ('topics', models.ManyToManyField(to='froide_pressconference.topic', verbose_name='topics')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='organization')),
                ('publicbody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicbody.publicbody', verbose_name='public body')),
            ],
            options={
                'verbose_name': 'speaker',
                'verbose_name_plural': 'speakers',
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sidenote', 'Sidenote'), ('question', 'Question'), ('speech', 'Speech'), ('followup', 'Follow-up'), ('interjection', 'Interjection')], max_length=50, verbose_name='kind')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('label', models.TextField(blank=True, verbose_name='label')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='froide_pressconference.section', verbose_name='section')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speeches', to='froide_pressconference.speaker', verbose_name='speaker')),
            ],
            options={
                'verbose_name': 'speech',
                'verbose_name_plural': 'speeches',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='pressconference',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='pressconference_unqique_slug'),
        ),
    ]
