# Generated by Django 5.2.10 on 2026-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0074_requestdraft_proof'),
        ('froide_pressconference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='foirequests',
            field=models.ManyToManyField(blank=True, to='foirequest.foirequest', verbose_name='related FOI requests'),
        ),
        migrations.AlterField(
            model_name='section',
            name='topics',
            field=models.ManyToManyField(blank=True, to='froide_pressconference.topic', verbose_name='topics'),
        ),
    ]
