# Generated by Django 5.2.10 on 2026-02-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('froide_pressconference', '0002_section_foirequests_alter_section_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressConferenceFacetsCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('terms', models.CharField(max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='pressconference',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'press conference', 'verbose_name_plural': 'press conferences'},
        ),
    ]
