# Generated by Django 5.2.10 on 2026-03-31 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_pressconference', '0003_pressconferencefacetscmsplugin_and_more'),
        ('publicbody', '0050_alter_publicbody_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressconferencecategory',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicbody.publicbody'),
        ),
    ]
