# Generated by Django 5.2.10 on 2026-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_pressconference', '0004_pressconferencecategory_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['order', 'id'], 'verbose_name': 'speech', 'verbose_name_plural': 'speeches'},
        ),
        migrations.AddField(
            model_name='pressconferencefacetscmsplugin',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressconferencefacetscmsplugin',
            name='interval',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week')], default='year', max_length=50),
        ),
        migrations.AddField(
            model_name='pressconferencefacetscmsplugin',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
