# Generated by Django 5.2.10 on 2026-04-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_pressconference', '0005_alter_speech_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['order', 'id'], 'permissions': (('can_use_presslaw', 'Can use press law'),), 'verbose_name': 'speech', 'verbose_name_plural': 'speeches'},
        ),
    ]
